name: 'AndroidNative Tests (macos)'

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  TEST:
    name: 'Test'
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: temurin
          cache: gradle

      - uses: actions/cache@v2
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan
      - uses: actions/cache@v2
        with:
          path: ${{ env.ANDROID_HOME }}/system-images
          key: ${{ runner.os }}-images

      - name: 'Build & publish to maven local directory.'
        run: ./gradlew publishToDirectorySnapshot

      - name: 'Run :sample android native tests.'
        run: ./gradlew sample:runAllAndroidNativeTests sample:killAndroidEmulators --stacktrace